const fakeProperties = [
    {
        id: 1,
        name: "Equitable Property",
        owner: "Owner 1",
        contact: "(123) 456-7890",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ultrices lobortis metus a luctus. Nunc eget felis sed nisi facilisis fermentum a eget ex. Vestibulum aliquam mi libero, suscipit mattis metus eleifend quis.",
        address: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        availability: [],
    },
    {
        id: 2,
        name: "Brick Cane",
        owner: "Owner 2",
        contact: "(123) 456-7890",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ultrices lobortis metus a luctus. Nunc eget felis sed nisi facilisis fermentum a eget ex. Vestibulum aliquam mi libero, suscipit mattis metus eleifend quis.",
        address: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        availability: [],
    },
    {
        id: 3,
        name: "Picket Fence",
        owner: "Owner 3",
        contact: "(123) 456-7890",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ultrices lobortis metus a luctus. Nunc eget felis sed nisi facilisis fermentum a eget ex. Vestibulum aliquam mi libero, suscipit mattis metus eleifend quis.",
        address: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        availability: [],
    },
    {
        id: 4,
        name: "Bold Realty",
        owner: "Owner 4",
        contact: "(123) 456-7890",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ultrices lobortis metus a luctus. Nunc eget felis sed nisi facilisis fermentum a eget ex. Vestibulum aliquam mi libero, suscipit mattis metus eleifend quis.",
        address: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        availability: [],
    },
    {
        id: 5,
        name: "Beacon Homes",
        owner: "Owner 5",
        contact: "(123) 456-7890",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ultrices lobortis metus a luctus. Nunc eget felis sed nisi facilisis fermentum a eget ex. Vestibulum aliquam mi libero, suscipit mattis metus eleifend quis.",
        address: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        availability: [],
    },
    {
        id: 6,
        name: "Blue Reef",
        owner: "Owner 6",
        contact: "(123) 456-7890",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ultrices lobortis metus a luctus. Nunc eget felis sed nisi facilisis fermentum a eget ex. Vestibulum aliquam mi libero, suscipit mattis metus eleifend quis.",
        address: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        availability: [],
    },
    {
        id: 7,
        name: "Silverbell",
        owner: "Owner 7",
        contact: "(123) 456-7890",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ultrices lobortis metus a luctus. Nunc eget felis sed nisi facilisis fermentum a eget ex. Vestibulum aliquam mi libero, suscipit mattis metus eleifend quis.",
        address: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        availability: [],
    },
    {
        id: 8,
        name: "Pinnacle",
        owner: "Owner 8",
        contact: "(123) 456-7890",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ultrices lobortis metus a luctus. Nunc eget felis sed nisi facilisis fermentum a eget ex. Vestibulum aliquam mi libero, suscipit mattis metus eleifend quis.",
        address: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        availability: [],
    },
    {
        id: 9,
        name: "Pagoda Partners",
        owner: "Owner 9",
        contact: "(123) 456-7890",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ultrices lobortis metus a luctus. Nunc eget felis sed nisi facilisis fermentum a eget ex. Vestibulum aliquam mi libero, suscipit mattis metus eleifend quis.",
        address: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        availability: [],
    },
    {
        id: 10,
        name: "Anchor Group",
        owner: "Owner 10",
        contact: "(123) 456-7890",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ultrices lobortis metus a luctus. Nunc eget felis sed nisi facilisis fermentum a eget ex. Vestibulum aliquam mi libero, suscipit mattis metus eleifend quis.",
        address: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        availability: [],
    },
    {
        id: 11,
        name: "Sovereign Realty",
        owner: "Owner 11",
        contact: "(123) 456-7890",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ultrices lobortis metus a luctus. Nunc eget felis sed nisi facilisis fermentum a eget ex. Vestibulum aliquam mi libero, suscipit mattis metus eleifend quis.",
        address: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        availability: [],
    },
    {
        id: 12,
        name: "Summerwood",
        owner: "Owner 12",
        contact: "(123) 456-7890",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ultrices lobortis metus a luctus. Nunc eget felis sed nisi facilisis fermentum a eget ex. Vestibulum aliquam mi libero, suscipit mattis metus eleifend quis.",
        address: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        availability: [],
    },
    {
        id: 13,
        name: "Soft spot",
        owner: "Owner 13",
        contact: "(123) 456-7890",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ultrices lobortis metus a luctus. Nunc eget felis sed nisi facilisis fermentum a eget ex. Vestibulum aliquam mi libero, suscipit mattis metus eleifend quis.",
        address: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        availability: [],
    },
]

export default fakeProperties;